# 將此內容加入你的 Home Assistant configuration.yaml

# Timer 設定（用於 ZBMini 藍圖）
timer:
  zbmini_switch_timer:
    duration: "00:00:01"
    name: "ZBMini 開關計時器"

# 如果你有多個 ZBMini 裝置，可以為每個裝置建立獨立的 timer
# 這樣可以避免裝置之間互相干擾
#
# timer:
#   zbmini_living_room_timer:
#     duration: "00:00:01"
#     name: "客廳 ZBMini 計時器"
#   
#   zbmini_bedroom_timer:
#     duration: "00:00:01"
#     name: "臥室 ZBMini 計時器"
#   
#   zbmini_kitchen_timer:
#     duration: "00:00:01"
#     name: "廚房 ZBMini 計時器"
